[uwsgi]
chdir = /mapproxy
chmod-socket = 777
gid = mapproxy
master = true
pidfile = /tmp/mapproxy.pid
processes = 2
pyargv = /mapproxy/config/mapproxy.yaml
socket = 0.0.0.0:8080
threads = 10
uid = mapproxy
wsgi-file = /mapproxy/app.py
