[uwsgi]
master = true
chdir = /mapproxy
pyargv = /mapproxy/config/mapproxy.yaml
wsgi-file = /mapproxy/app.py
pidfile = /tmp/mapproxy.pid
socket = 0.0.0.0:8080
processes = $(UWSGI_PROCESSES)
threads = $(UWSGI_THREADS)
chmod-socket = 777
vacuum = true
uid = mapproxy
gid = mapproxy
